name: ci-docker-build

on:
  push:
    branches: [ "latest" ]
  pull_request:
    branches: [ "latest" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Image Build
      run: docker build . --file Dockerfile --tag ghcr.io/20lush/lush-dev:$(date +%s)
